### ISSUE TITLE
I think it's hard in Kotlin，so do you have  a java version？

### ISSUE THREAD

**Issue by wangogo** [cortinico/myonnaise#11]
hello ：
I met some difficulties in your Kotlin，for example：not understand the meaning of your writing，so do you  have  a java version？so，if any ，can you send me a copy。my email：wangogo@outlook.com  。Thank you very much

**Comment by cortinico** [comment]
Hi @wangogo 
This project is entirely in Kotlin I'm sorry.
You could actually checkout the git history before I rewrote everything in Kotlin: https://github.com/cortinico/myonnaise/tree/27352cd9badf26fd36b174cb14d7e0e105701361
Please note that I also added several new features during the rewrite.
